# Generated by Django 3.1.7 on 2021-04-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210411_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='header',
            field=models.ImageField(blank=True, default='orange.jpg', null=True, upload_to=''),
        ),
    ]
