# Generated by Django 4.1.7 on 2023-03-31 15:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='Default_Pic_lk0scq.webp', max_length=255, null=True, verbose_name='image'),
        ),
    ]
