# Generated by Django 4.1.6 on 2023-02-27 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0006_remove_comment_like_remove_post_like_comment_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='com_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
