# Generated by Django 4.1.6 on 2023-02-28 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_postmedia_media_thread_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DM', 'DM'), ('FOLLOW', 'FOLLOW'), ('LIKE', 'LIKE'), ('COMMENT', 'COMMENT')], max_length=10),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_media', to='social.post'),
        ),
    ]
