# Generated by Django 4.1.6 on 2023-03-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_alter_thread_receiver_alter_thread_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created',)},
        ),
    ]
