# Generated by Django 4.1.7 on 2023-03-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
