# Generated by Django 4.1.7 on 2023-03-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
